ENABLE_TESTING()

IF (NOT DEFINED WORKSPACE_ROOT)
  IF ($ENV{API_WORKSPACE})
    SET (WORKSPACE_ROOT "$ENV{API_WORKSPACE}" CACHE STRING "path to api projects")
  ELSE($ENV{API_WORKSPACE})
    IF (MSVC)
        SET (WORKSPACE_ROOT "$ENV{HOME}\\develop\\api" 
             CACHE STRING "path to api projects")
    ELSE (MSVC)
        SET (WORKSPACE_ROOT "$ENV{HOME}/develop/api" 
             CACHE STRING "path to api projects")
    ENDIF (MSVC)
  ENDIF($ENV{API_WORKSPACE})
ENDIF(NOT DEFINED WORKSPACE_ROOT)


MESSAGE(STATUS "WORKSPACE_ROOT set to: ${WORKSPACE_ROOT}")

IF(NOT DEFINED EXECUTABLE_OUTPUT_PATH)
  SET (EXECUTABLE_OUTPUT_PATH ${PROJECT_BINARY_DIR}/build/bin)
ENDIF(NOT DEFINED EXECUTABLE_OUTPUT_PATH)

IF(NOT DEFINED LIBRARY_OUTPUT_PATH)
  SET (LIBRARY_OUTPUT_PATH ${PROJECT_BINARY_DIR}/build/lib)
ENDIF(NOT DEFINED LIBRARY_OUTPUT_PATH)

#set the compiler flags for this project
INCLUDE("cmake/compilers.cmake")
INCLUDE_DIRECTORIES(include)

link_directories(${LIBRARY_OUTPUT_PATH})
