IF (NOT DEFINED HAVE_COMPILERS)
MACRO(ADD_RELEASE_CXXFLAGS flags)
  SET(CMAKE_CXX_FLAGS_RELEASE ${CMAKE_CXX_FLAGS_RELEASE} ${${flags}})
ENDMACRO(ADD_RELEASE_CXXFLAGS)

MACRO(ADD_DEBUG_CXXFLAGS flags)
  SET(CMAKE_CXX_FLAGS_DEBUG ${CMAKE_CXX_FLAGS_DEBUG} ${${flags}})
ENDMACRO(ADD_DEBUG_CXXFLAGS)

MACRO(ADD_DEBUG_LINKFLAGS flags)
  SET(CMAKE_EXE_LINKER_FLAGS_DEBUG ${CMAKE_EXE_LINKER_FLAGS_DEBUG} ${@flags@})
ENDMACRO(ADD_DEBUG_LINKFLAGS)

####
# set some good compiler flags for MSVC
####
IF (MSVC)
    SET (CMAKE_AR "${CMAKE_AR} /nologo")

    ADD_DEFINITIONS( /D WIN32 /EHsc /W1)
    ADD_DEFINITIONS( /D WIN32_LEAN_AND_MEAN)
    # LINKFLAGS += "/NODEFAULTLIB:LIBC" ;
    ADD_RELEASE_CXXFLAGS(/O2 /GB /D NDEBUG)
    ADD_DEBUG_CXXFLAGS(/Od /Zi /Yd)
      #    ADD_DEBUG_LINKFLAGS(/NODEFAULTLIB:MSVCRT)
    # LINKFLAGS += "/DEBUG"
ENDIF (MSVC)

####
# set some good default compiler flags for GCC
####
IF (CMAKE_COMPILER_IS_GNUCXX)
  ADD_DEFINITIONS(-Wall -W -Wcast-align -Wwrite-strings)
  ADD_DEFINITIONS(-D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS)
  ADD_DEBUG_CXXFLAGS(-g -D_THREAD_SAFE -pthread)
  IF (CMAKE_SYSTEM_NAME STREQUAL "hpux")
    ADD_DEBUG_CXXFLAGS(-DDISABLE_WIDE_CHAR_SUPPORT)
    ADD_RELEASE_CXXFLAGS(-DDISABLE_WIDE_CHAR_SUPPORT -O2 -DNDEBUG)
  ENDIF (CMAKE_SYSTEM_NAME STREQUAL "hpux")
  IF (CMAKE_SYSTEM_NAME STREQUAL "aix")
    SET(CMAKE_CXX_COMPILER "/home/mgariss/bin/g++.rb")
    ADD_RELEASE_CXXFLAGS(-DNDEBUG)
  ENDIF (CMAKE_SYSTEM_NAME STREQUAL "aix")
  IF (CMAKE_SYSTEM_NAME STREQUAL "aix") # Otherwise
    ADD_RELEASE_CXXFLAGS(-O2 -DNDEBUG)
  ENDIF (CMAKE_SYSTEM_NAME STREQUAL "aix") # Otherwise
ENDIF (CMAKE_COMPILER_IS_GNUCXX)

SET(HAVE_COMPILERS 1)
ENDIF(NOT DEFINED HAVE_COMPILERS)
